### ISSUE TITLE
[M04] Nested stack-a nie można stworzyć z dołączonego skryptu

### ISSUE THREAD

**Issue by pnowosie** [pnowosie/aws-devops#3]
Skrypt tworzy poprawnie:
- artifact-bucket
- root-packaged.yaml
- przenosi oba template-y (log-bucket & website-bucket) do artifact-bucket

Błędy:
- Problem ze stworzeniem log-bucket
  Błąd z eventów stacka: `website-nested-nested-dev`

> S3 error: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Comment by pnowosie** [comment]
**Rozwiązanie** (manualne :cry: )

W utworzony w wyniku pakowania `root-packaged.yaml` w resources są url-e do template-ów z `artifact-bucket`, e.g.:
```yaml
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/website-nested-artifact-dev-artifactbucket-abcd0000/abcd0000abcd0001.template
```

Należy podmienic url na ten widoczny w widoku obiektu z artifact bucket:
```yaml
    Properties:
      TemplateURL: https://website-nested-artifact-dev-artifactbucket-abcd000.s3.eu-west-1.amazonaws.com/abcd0000abcd0001.template
```

**Comment by karolinaboboli-chmurowisko** [comment]
To automatycznie powinno się dziać
Czy gdzieś czasem nie zamieniły się u Ciebie regiony? W 1. url masz eu-central-1 (Frankfurt) a deployment idzie do Irlandii 
(zgodnie z tym co jest w skrypcie)

**Comment by pnowosie** [comment]
Ha! @karolinaboboli-chmurowisko - dobre spostrzeżenie. Moj `default.region` w aws-cli to właśnie Frankfurt (eu-central-1).
Dodałem opcję do `package="aws cloudformation package ... --region eu-west-1"` ale to nie pomogło...

Zmieniłem domyślny region na Irlandię
`aws configure set default.region eu-west-1`

Teraz stack tworzy się poprawnie!
